### ISSUE TITLE
iTerm2 Build 2.9.20160206 not supported

### ISSUE THREAD

**Issue by timhogenbirk** [fitztrev/shuttle#164]
iTerm2 Build 2.9.20160206 will not open if a connection is selected.

**Comment by nightmare-rg** [comment]
+1

same here.

**Comment by krapivchenkon** [comment]
the same issue:
  "terminal": "iTerm",
  "iTerm_version": "stable",

both "inTerminal": "tab" and "inTerminal": "new" doesn't work.
Even shuttle->Settings->Edit stopped working

**Comment by aamnah** [comment]
+1 

same here, but kinda expected it since Build 2.9.20160206 is a beta release..

**Comment by wujku** [comment]
+1

**Comment by blerest** [comment]
+1
same here.

**Comment by rgunst** [comment]
+1

**Comment by rgunst** [comment]
Same thing here.
But after replacing .shuttle.json with this config it works for me.
{
  "editor": "default",
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",  
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    }
  ]
}

**Comment by nightmare-rg** [comment]
I tested it with this, but not working:

`{
        "_comments": [
                "Valid terminals include: 'Terminal.app' or 'iTerm'",
                "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
                "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
        ],
        "launch_at_login": true,
        "show_ssh_config_hosts": true,
        "editor": "default",
        "terminal": "iTerm",
        "iTerm_version": "nightly",
        "default_theme": "Default",
        "open_in": "tab",
        "ssh_config_ignore_hosts": [],
        "ssh_config_ignore_keywords": ["git"],
        "hosts": [
        { "test1": [ ] },
        { "test2": [ ] },
        { "test3": [ ] },
        { "test4": [ ] },
        ]
}`

**Comment by aamnah** [comment]
i tried `"iTerm_version": "nightly"` too, didn't work for me.

**Comment by ekurennyy** [comment]
+1

**Comment by udayms** [comment]
@rgunst's solution worked for me. Had to change default_theme, iterm_version, open_in to the values in @rgunst's solution.

**Comment by Kami-no** [comment]
+1 but solution @rgunst helped me too.

- 	"editor": "default",
-	"terminal": "iTerm",
-	"iTerm_version": "nightly",
-	"open_in": "tab",

**Comment by thshdw** [comment]
Hello All, 
The nightly builds should be working. Until 1.2.6 is out make sure that you have all the new directives set.  The new syntax is listed on the readme.md

**Comment by thshdw** [comment]
fixed in release v.1.2.6 pull #165

**Comment by apfelbox** [comment]
I have iTerm Build 2.9.20160206, Shuttle 1.2.6 and the following config:

```json
{
	"editor": "default",
	"terminal": "iTerm",
	"launch_at_login": true,
	"show_ssh_config_hosts": true,
	"ssh_config_ignore_hosts": [],
	"ssh_config_ignore_keywords": [],
	"open_in": "tab",
	"iTerm_version": "nightly",
	"hosts": [
		{
			"Folder": [
				{"name": "server 1", "cmd": "ssh user@example.org"}
			]
		}
       ]
}
```

It there something wrong in the config?

but it still only brings the iTerm window to front, but doesn't execute the commands.

**Comment by thshdw** [comment]
@apfelbox 

I have not tested that release... only the stable and nightly versions are applescript tested and supported. 

I'm using the latest nightly and its working for me using your config.
https://iterm2.com/downloads/nightly/iTerm2-2_9_20160311-nightly.zip

Delete your current iTerm build from applications and put the the new nightly in. That should solve your issue. :smile:

**Comment by apfelbox** [comment]
@thshdw thanks for your quick response!

I just downloaded the …0311 build and still have the same issue.

**Comment by thshdw** [comment]
@apfelbox Contact me on gitter. Link is on the main page.

**Comment by thshdw** [comment]
Hello All,
I want to make sure that everyone is able to use iTerm nightly. There are 11 users on this thread and I want to make sure that you all have a functioning sshuttle. 

Make sure that you check out the new syntax. We have a lot of new directives and while I have done my best to not break previous configs some of you may have to update your shuttle.json with the new directives. 

Also make sure that your iTerm's default profile is called "Default" See below.

<img width="917" alt="screen shot 2016-03-11 at 10 54 40 am" src="https://cloud.githubusercontent.com/assets/4992951/13710816/863cb0b8-e778-11e5-8c56-a0ff3153ac26.png">

If your default profile is not called "Default" and if you don't specify a default theme iTerm may not open. Because I need to handle for situations where a theme may be spelled wrong or perhaps may not exist I have to fall back on the default. In this case I'm relying on the theme that iTerm ships with which is called "Default"... However if you change this by renaming it or deleting it then the applescipts have no fallback and when a theme is not set the "Default" is missing and iTerm wont open. 

Check these things and contact me if you have problems. 

Thanks, 
:smile:

**Comment by apfelbox** [comment]
For the record: I had renamed my profile. Renamed it back to "Default" and now everything works! :tada:

**Comment by thshdw** [comment]
@apfelbox Awesome! Thanks for updating the community :smile:

**Comment by blerest** [comment]
@thshdw yeah the issue has been fixed. Thank you for that.
