### ISSUE TITLE
Backslash is printed when escaping double quotes in cmd

### ISSUE THREAD

**Issue by Franklin88** [fitztrev/shuttle#194]
**Test configuration:**
{
			"name": "Test escaping characters",
			"cmd": "echo \"Hello\"; echo 'world'; "
}

**Output:**
$ echo \"Hello\"; echo 'world'; 
"Hello"
world

**Expected:**
$ echo "Hello"; echo 'world'; 
Hello
world

**Notes:**
Same result using unicode \u0022 => {"cmd": "echo \u0022Hello\u0022; echo 'world'; "}

**Environment**:
MacOS 10.10.5
Shuttle v1.2.7
iTerm2 Build 3.0.8
Terminal.app 2.5.3 (343.7)

**Comment by thshdw** [comment]
What are you wanting to accomplish? It seems that its working as expected. 
If I manually type in terminal ```echo \"Hello\"``` I get the expected output of ```"Hello"```
I get this because I'm escaping the double quotes and they print. 

If I manually type in terminal ```echo "Hello"``` I get the expected output of ```Hello```
I get this because I'm **Not** escaping the double quotes so they don't print

**Comment by Franklin88** [comment]
Probably I'm not fully understanding how escaping works. Let me give you a real life example.
I want to run the following command: `ps -ef | grep java | awk '{print "Pid: "$2, $8, $9, $10}'`

If I insert this in the shuttle.json config file I have to escape the double quotes of the _print_ part otherwise it breaks the config file, so my cmd looks like this: `"cmd": "ps -ef | grep java | awk '{print \"Pid: \"$2, $8, $9, $10}'"`

But when I execute this through shuttle it runs it with the backslashes breaking the actual command:
```
$ ps -ef | grep java | awk '{print \"Pid: \"$2, $8, $9, $10}'
awk: syntax error at source line 1
 context is
       	{print >>>  \ <<< "Pid: \"$2, $8, $9, $10}
awk: illegal statement at source line 1
```

What am I doing wrong?

**Comment by Franklin88** [comment]
Btw, if I apply the same to name tag it works like I would expect:

Name tag is configured as follows:
`"name": "ps -ef | grep java | awk '{print \"Pid: \"$2, $8, $9, $10}'"`

And in the menu it shows up without the backslashes:

> ps -ef | grep java | awk '{print "Pid: "$2, $8, $9, $10}'

**Comment by thshdw** [comment]
@Franklin88 Awesome, Thanks for the real world examples. I'll look into a solution.

**Comment by thshdw** [comment]
@Franklin88 Seems that we have a bug with the way double quotes are escaped.

**Comment by Franklin88** [comment]
Great! Thx

**Comment by WorldWideWebb** [comment]
Not sure if this is the same issue or not, but I'm having an issue with wanting to use a backslash in my command and it not working. I try running it from the menu, and nothing happens (as soon as I remove the backslash, it works fine). It's the one right after "Mobile":

```
		{
			"name": "Run local site",
			"cmd": "cd /Users/myusername/Library/Mobile\\ Documents/com~apple~CloudDocs/Sites/mysitename && commandhere"
		}
```

I tried it with and without the double backslash, and neither works.

**Comment by thshdw** [comment]
@WorldWideWebb I have confirmed that the bug is causing this issue as well. I'll try to have 1.2.8 for the weekend.

**Comment by WorldWideWebb** [comment]
Anything new on this bug?

**Comment by thshdw** [comment]
It's resolved on my dev system. Doing some more testing before I release. I can send you what I have if you want to test.

**Comment by thshdw** [comment]
Should be fixed in v1.2.8. Let me know if its not working for you.

**Comment by WorldWideWebb** [comment]
Works great! Thanks!

**Comment by thshdw** [comment]
@WorldWideWebb Thanks for the update!

**Comment by Franklin88** [comment]
Hi! Thanks for the new release. The escaping works much better now. However I'm still experiencing some problems when the shuttle.json file is parsed. 
In some cases escaping the semicolon when concatenating commands fails. For example:

Let's say I want to open Google and close the terminal after that (just as an example):

**Configuration:**
{
    "cmd": "open https://www.google.es; exit",
    "inTerminal": "new",
    "name": "Google"
}

**Output:**
open https://www.google.es\; exit
The file /Users/foobar/exit does not exist.

As can be seen a backslash is printed before the semicolon which breaks the command. As curiosity, if I put a space before the semicolon it works as expected:

 "cmd": "open https://www.google.es ; exit"

However, I understand that it should work with and without a space like it does from the command line.

**Comment by thshdw** [comment]
@Franklin88 
I'll look into this... however you should not need the open directive try command:

```"cmd": https://www.google.es"```

this should open in the default browser.
